### ISSUE TITLE
After CSRF implementation clear hook throws error

### ISSUE THREAD

**Issue by sonofmun** [Code-Pop/Nuxt_Authentication#1]
After adding the CSRF protection in the session-guard.ts file, the clear hook starts throwing an error:
```
ERROR  [nuxt] [request error] [unhandled] [500] Cannot destructure property 'csrfToken' of '(intermediate value)' as it is undefined.
  at Object.handler (./server/middleware/session-guard.ts:24:1)  
  at async ./node_modules/h3/dist/index.mjs:1975:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2266:7)
```
It appears that this is because the clear hook event has an undefined request body (the following is from the H3Event object)
```
_method: 'DELETE',
  _path: '/api/_auth/session',
  _headers: undefined,
  _requestBody: undefined,
```
So when session-guard.ts comes to the line `const { csrfToken } = await readBody<{ csrfToken?: string }>(event)` it throws the error because the event body is undefined.
I am tempted to exclude /api/_auth/session DELETE from this CSRF check since the point is to logout the user and even if we had the check and someone tried a CSRF attack to /api/_auth/session DELETE, the result would be to log the user out and delete the session, which is what the clear hook does anyways. But I am not sure if there might be unexpected security consequences to removing /api/_auth/session DELETE from the CSRF check.

**Comment by tutorialcode** [comment]
I left the solution in the L6-end branch.
